Completed feature (#5), user can now post and get information for sho…
YunCYang/wicked-sales-js pull request #5
Opened 2020-01-14 23:05 UTC by YunCYang

![wicked_sale_feature_5_cart_backend](https://user-images.githubusercontent.com/25411965/72390271-28e62600-36df-11ea-87be-104608030fa4.gif)
…pping cart on backend

2020-01-14 23:12 UTC, thebearingedge requested changes

2020-01-14 23:12 UTC, thebearingedge commented on server/index.js
> +  if (!req.session.cartId) return [];
Be sure to actually respond here or the client will hang and wait forever.

2020-01-14 23:12 UTC, thebearingedge commented on server/index.js
> +        next(new ClientError(`Requested product (id: ${req.body.productId}) does not exist in the database.`, 404));
You should `throw` this error or `return Promise.reject(new ClientError(/* etc */))` to shortcut to your `catch()` callback.

2020-01-14 23:18 UTC, YunCYang commented
![image](https://user-images.githubusercontent.com/25411965/72391053-0ce38400-36e1-11ea-98f5-3946340a820f.png)

2020-01-15 00:56 UTC, thebearingedge approved these changes

2020-01-15 00:56 UTC, merged